[0m12:51:11.475109 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9124c1cd50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f91251e5dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9124c1d810>]}


============================== 12:51:11.492783 | 97beb8bd-28cf-4aec-a5e5-91b80a60908f ==============================
[0m12:51:11.492783 [info ] [MainThread]: Running with dbt=1.7.4
[0m12:51:11.501157 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/habte/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:51:11.520853 [error] [MainThread]: Encountered an error:
'NoneType' object is not subscriptable
[0m12:51:11.612571 [error] [MainThread]: Traceback (most recent call last):
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 90, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/requires.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/cli/main.py", line 515, in init
    results = task.run()
              ^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/task/init.py", line 317, in run
    profile_name = self.get_profile_name_from_current_project()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/habte/anaconda3/lib/python3.11/site-packages/dbt/task/init.py", line 142, in get_profile_name_from_current_project
    return dbt_project["profile"]
           ~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

[0m12:51:11.623768 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 0.16425088, "process_user_time": 5.980966, "process_kernel_time": 0.399242, "process_mem_max_rss": "101024", "process_in_blocks": "112", "process_out_blocks": "8", "command_success": false}
[0m12:51:11.635168 [debug] [MainThread]: Command `dbt init` failed at 12:51:11.634508 after 0.18 seconds
[0m12:51:11.637746 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9124c29fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f9124c1f010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f91250ccdd0>]}
[0m12:51:11.640170 [debug] [MainThread]: Flushing usage events
